name: github action workflow
on:
  push:
    branch:
      - main

env:
  IMAGE_NAME: v2
  DOCKERHUB_REPOSITORY: mlrene/pipeline_image
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t $IMAGE_NAME .
      - name: tag docker image
        run: docker image tag $IMAGE_NAME $DOCKERHUB_REPOSITORY:v2
      - name: Push image to dockerhub
        run: docker push $DOCKERHUB_REPOSITORY:$IMAGE_NAME
      - name: Run docker image
        run: docker run -d -p 8000:80 $DOCKERHUB_REPOSITORY:$IMAGE_NAME
